services:
  api_predict:
    build:
      context: .
      dockerfile: api/predict/Dockerfile
    container_name: api_predict
    ports:
      - "8002:8000"
    volumes:
      - ./api/predict:/app/predict # TODO remove for production
    networks:
      - backend

  api_data:
    build:
      context: .
      dockerfile: api/data/Dockerfile
    container_name: api_data
    ports:
      - "8001:8000"
    volumes:
      - ./api/data:/app/data # TODO remove for production
    environment:
      SUPABASE_URL: http://kong:8000  # Modification ici
      SUPABASE_KEY: ${SUPABASE_KEY}
    networks:
      - backend

  streamlit:
    build:
      context: streamlit
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app # TODO remove for production
    environment:
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - backend

  # db:
  #   build:
  #     context: ./app/database
  #     dockerfile: Dockerfile
  #   container_name: db
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - app_network

networks:
  backend:
    name: backend
    external: true

# volumes:
#   db_data:
#     driver: local
