services:
  api_predict:
    build:
      context: .
      dockerfile: api/predict/Dockerfile
    container_name: api_predict
    ports:
      - "8002:8000"
    volumes:
      - ./api/predict:/app/predict # TODO remove for production
    networks:
      - backend

  api_data:
    build:
      context: .
      dockerfile: api/data/Dockerfile
    container_name: api_data
    ports:
      - "8001:8000"
    volumes:
      - ./api/data:/app/data # TODO remove for production
    environment:
      SUPABASE_URL: http://kong:8000
      SUPABASE_KEY: ${SUPABASE_KEY}
    networks:
      - backend

  streamlit:
    build:
      context: streamlit
      dockerfile: Dockerfile
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app # TODO remove for production
    environment:
      - TMDB_API_TOKEN=${TMDB_API_TOKEN}
      - SUPABASE_URL=http://kong:8000
      - SUPABASE_KEY=${SUPABASE_KEY}
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true
