services:
  api-predict:
    build:
      context: ..
      dockerfile: app/api/predict/Dockerfile
    image: api-predict
    container_name: api-predict
    ports:
      - "8002:8000"
    volumes:
      - ./api/predict:/app/predict # TODO remove for production
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
    networks:
      - backend

  streamlit:
    build:
      context: streamlit
      dockerfile: Dockerfile
    image: streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app # TODO remove for production
    environment:
      TMDB_API_TOKEN: ${TMDB_API_TOKEN}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${ANON_KEY}
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true
