# airflow/docker-compose.override.yml

services:
  airflow-webserver:
    networks:
      - airflow_default
  airflow-scheduler:
    networks:
      - airflow_default
  airflow-worker:
    networks:
      - airflow_default
      - backend
  airflow-triggerer:
    networks:
      - airflow_default
  airflow-init:
    networks:
      - airflow_default
  postgres:
    networks:
      - airflow_default
  redis:
    networks:
      - airflow_default
networks:
  airflow_default:
    driver: bridge
  backend:
    external: true
