# airflow/docker-compose.override.yml

services:
  airflow-webserver:
    networks:
      - backend
  airflow-scheduler:
    networks:
      - backend
  airflow-worker:
    networks:
      - backend
  airflow-triggerer:
    networks:
      - backend
  airflow-init:
    networks:
      - backend
  postgres:
    networks:
      - backend
  redis:
    networks:
      - backend

networks:
  backend:
    external: true
