name: Build and Push Docker Images

on:
  push:
    # branches:
    #   - master
    tags:
      - 'v*.*.*'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile.apipredict
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-predict:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-predict:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/api-predict:${{ github.ref_name }}

      - name: Build and push Streamlit image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile.streamlit
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:${{ github.ref_name }} 
